[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pump = "9tfxEcc7UBpJhHofsohtYhgd4oe9Fxcp4e8uENCSas9K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/isaac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
