[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pump = "CaCK9zpnvkdwmzbTX45k99kBFAb9zbAm1EU8YoVWTFcB"
raydium_adapter = "2q8EXsQ99V7F3pQq8gGjt6o3vijqjCEYazA2Yh4S4ray" # placeholder id for local adapter

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/isaac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
