name: IDL drift check

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  idl-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        run: |
          npm ci

      - name: Verify Docker is available
        run: docker --version

      - name: Run idl:check (fail on drift)
        run: |
          bash scripts/idl:check